import json
from datetime import datetime, timezone
from pathlib import Path

from risk_control_agent.recommendations import build_operations_recommendations
from risk_control_agent.report_sections import (
    render_appendix,
    render_data_availability,
    render_executive_summary,
    render_human_confirmation_items,
    render_key_metric_findings,
    render_limitations,
    render_overall_risk_level,
    render_root_cause_findings,
    render_segment_contribution_findings,
    render_triggered_alert_rules,
)


PROJECT_PHASE = "Phase 8 - Risk Report Generation"
DEFAULT_FOOTER = (
    "This report is generated by Risk Control Agent for educational and portfolio "
    "demonstration purposes. It does not constitute real financial risk advice or "
    "an automated credit decision."
)


def load_json_if_exists(path: str | Path):
    """Load JSON if it exists, otherwise return None."""
    path = Path(path)
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def build_report_context(alert_summary=None, root_cause_summary=None, metadata=None) -> dict:
    """Build report context from structured summaries."""
    return {
        "alert_summary": alert_summary,
        "root_cause_summary": root_cause_summary,
        "metadata": metadata or {},
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def validate_report_inputs(alert_summary=None, root_cause_summary=None) -> dict:
    """Validate whether report generation is allowed."""
    if not alert_summary and not root_cause_summary:
        return {
            "can_generate": False,
            "warnings": ["No alert summary or root cause summary was provided."],
            "inputs_used": [],
        }
    inputs_used = []
    if alert_summary:
        inputs_used.append("alert_summary")
    if root_cause_summary:
        inputs_used.append("root_cause_summary")
    return {"can_generate": True, "warnings": [], "inputs_used": inputs_used}


def _render_recommendations(alert_summary, root_cause_summary, recommendation_config) -> str:
    recommendations = build_operations_recommendations(alert_summary, root_cause_summary, recommendation_config or {})
    if not recommendations:
        return "## Operations Recommendations\n\nNot available in this run."
    lines = ["## Operations Recommendations", ""]
    for item in recommendations:
        marker = " Requires human confirmation." if item.get("human_confirmation_required") else ""
        lines.append(f"* {item.get('recommendation')}{marker}")
    return "\n".join(lines)


def generate_markdown_report(report_context, template_config=None, recommendation_config=None) -> str:
    """Generate deterministic Markdown report from structured inputs."""
    alert_summary = report_context.get("alert_summary")
    root_cause_summary = report_context.get("root_cause_summary")
    validation = validate_report_inputs(alert_summary, root_cause_summary)
    if not validation["can_generate"]:
        raise ValueError("Cannot generate report without alert summary or root cause summary.")

    template_config = template_config or {}
    title = template_config.get("report_name", "Risk Analysis Report")
    footer = template_config.get("footer_disclaimer", DEFAULT_FOOTER)
    safety_notes = template_config.get("safety_notes", [])

    sections = [
        f"# {title}",
        "",
        f"Generated at: `{report_context.get('generated_at')}`",
        "",
        render_executive_summary(alert_summary, root_cause_summary),
        render_overall_risk_level(alert_summary),
        render_triggered_alert_rules(alert_summary),
        render_key_metric_findings(alert_summary),
        render_root_cause_findings(root_cause_summary),
        render_segment_contribution_findings(root_cause_summary),
        render_data_availability(alert_summary, root_cause_summary),
        _render_recommendations(alert_summary, root_cause_summary, recommendation_config),
        render_human_confirmation_items(alert_summary, root_cause_summary),
        render_limitations(),
        render_appendix(alert_summary, root_cause_summary),
        "## Safety Note",
        "\n".join(f"* {note}" for note in safety_notes) if safety_notes else "Final decisions require human review and approval.",
        "## Footer Disclaimer",
        footer,
    ]
    return "\n\n".join(sections) + "\n"


def save_markdown_report(markdown_text: str, output_path: str | Path) -> Path:
    """Save Markdown report."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown_text, encoding="utf-8")
    return path


def generate_report_manifest(report_path, status, inputs_used, warnings=None) -> dict:
    """Generate report manifest metadata."""
    return {
        "report_path": str(report_path) if report_path else None,
        "status": status,
        "inputs_used": inputs_used,
        "warnings": warnings or [],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "project_phase": PROJECT_PHASE,
    }


def save_report_manifest(manifest: dict, output_path: str | Path) -> Path:
    """Save report manifest JSON."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(manifest, file, indent=2, ensure_ascii=False)
    return path

